pipeline{
    agent{
         node {
        label 'agent-1'
    }
    }
    options {
        timeout(time: 1, unit: 'HOURS') 
         disableConcurrentBuilds()
    }
    stages{
         stage("init")
         {
        steps{
             
            sh """
            cd 01-vpc
            terraform init -reconfigure
            """
            }
         }
        stage("plan")
         {
        steps{
            
            sh """
            cd 01-vpc
            terraform plan
            """   
          
        }
    }
    stage("apply")
    {
        steps{
             
            sh """
            cd 01-vpc
            terraform apply -auto-approve
            """
        }
    }

 post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'I will always say success!'
        }
                failure { 
            echo 'I will always say success!'
        }
    }
}
}